# Example kitty configuration file.

# Default font size and family
font_size 12.0
font_family Hack

# Colorscheme
theme Default

# Miscellaneous
hide_tab_bar_when_only_one_tab true
window_padding_width 5
mouse_hide_wait 3.0
